### ISSUE TITLE
Windows Defender false positive?

### ISSUE THREAD

**Issue by ItzMeRainbow** [donnaken15/FastGH3#10]
(Terms: FastGH3.exe is the launcher/song converter and settings, and game.exe is Guitar Hero 3 itself)

**Summarize**
Windows Defender picks up helix.exe and makefsb.exe as a trojan

**To Reproduce**
1. Extract FastGH3
2. Windows Defender will say that threats were found 

**Screenshots**

**When I downloaded this mod/what version I'm using (most likely required)**
Latest dev build as of 27/12/23 NZDT

**Desktop (Optional, but could help figure out system specific problems):**
 - OS: Windows 10 build 19045.3803

***Do you have these installed: (write an X in the box if you have the following software)***
 - [ X ] [DirectX 9](http://localhost/fastgh3/redist.php?f=1)
 - [ X ] [Visual C++ 2005](http://localhost/fastgh3/redist.php?f=2)
 - [ X ] [.NET Framework 4](http://localhost/fastgh3/redist.php?f=3)

(These are vital to using the mod!)

**Comment by donnaken15** [comment]
I've had someone ask me about this as well but just for Helix EXE
I don't know if the last time I built it before I did in the newest commit was no longer false flagged as they haven't responded back
Did this happen if you extracted the mod from this commit (the false flag that other user had)?: 24d0738
makefsb false flag very obviously makes no sense as it just puts MP3s in a container
I don't use the new Defender UI, but did it put the executables in quarantine and allow you to restore them?

**Comment by ItzMeRainbow** [comment]
![image](https://github.com/donnaken15/FastGH3/assets/103361477/0b567fc3-880b-4dc2-85f9-925f1935f88c)
![image](https://github.com/donnaken15/FastGH3/assets/103361477/f7d9fb7d-f8e7-42b2-b69e-028669d565ae)
It auto deletes helix even if i select allow on device

**Comment by donnaken15** [comment]
Weird, and stupid for how Windows handles that, and for detecting false positives anyway
You could try excluding Defender from doing anything with where you extracted the mod by running `Add-MpPreference -ExclusionPath "<dir>"` in Powershell

**Comment by ItzMeRainbow** [comment]
![image](https://github.com/donnaken15/FastGH3/assets/103361477/5af845b0-02e2-4a6e-b5c7-2b7ed3f7faf7)

**Comment by donnaken15** [comment]
??????????????????????
