### ISSUE TITLE
Complete lack of guitar controller support

### ISSUE THREAD

**Issue by Meru1337** [donnaken15/FastGH3#11]
Why am I unable to use any guitar that I own? It's like the game assumes that it's x-input and I cannot rebind my keys. It works with CH, it works with GH2 on Emulator, the controller works fine. Why does this only support keyboards? Truly awful experience.

**Comment by ItzMeRainbow** [comment]
I think gh3 maps anything it doesnt understand using the controller mappings

**Comment by donnaken15** [comment]
> Why am I unable to use any guitar that I own? It's like the game assumes that it's x-input and I cannot rebind my keys. It works with CH, it works with GH2 on Emulator, the controller works fine. Why does this only support keyboards? Truly awful experience.

what specific guitars do you own????

the game recognizes controllers that use XInput and DInput

let me guess, Arduino or Wiitar? there's tutorials on YouTube on how to make it work on GH3, and/or there's specific software you can use like Xpadder, JoyToKey, or x360ce

and what do you mean about rebinding keys

even if a controller indicates that it's a guitar in hardware (assuming that's how it works), sometimes GRYBO buttons, etc aren't mapped to the same literal gamepad buttons as official GH guitars do

**Comment by donnaken15** [comment]
I realize what this is about now

Did you read this second bullet point completely?

https://github.com/donnaken15/FastGH3#extra-steps
||this option was awkwardly named to indicate that it should be used if your controllers change slots in in-game when plugging and unplugging controllers, but then requires you to press a button on a controller to play the song with said controller||

and keyboard bind changing is in FastGH3 settings (settings.bat)

**Comment by Meru1337** [comment]
Oh yes, I read everything. All that does is enable my orange and red buttons and my strum bar. And yes, I have an arduino Wii guitar and a raphnet knock off Wii guitar. They work fine in every other piece of software that lets you map controls. (All software ever lol)

The auto-map function does not support them, clearly. 

I've ran it through Joy2Key and the latency introduced is unbearable.

It's a shame because the zones look awesome and the other features are cool. I'll stick to CH or PS2 emulation I guess lol.

**Comment by ZedekThePlagueDoctor** [comment]
> They work fine in every other piece of software that lets you map controls. (All software ever lol)

That's because "all software ever" uses any device that can be recognized as a controller. You **MUST** use an XInput device for FastGH3 / GH3 to recognize it. This has always been the case with GH3.

Donnaken has given instructions specifically on how to get this working:

> there's tutorials on YouTube on how to make it work on GH3, and/or there's specific software you can use like Xpadder, JoyToKey, or x360ce

**Comment by ItzMeRainbow** [comment]
GH3 doesn't know what controller you're using so it just defaults to the controller layout
