### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by Dark-speedruns** [donnaken15/FastGH3#12]
i was trying to play on linux using wine but inputs on my xplorer were fucked, cant play customs, cant do anything but game runs smoothly

**Comment by donnaken15** [comment]
Don't know how that could happen other than XInput being messed up? Did using the keyboard work? One person got it working once: https://twitter.com/LeafyGH/status/1525898263072714752

**Comment by Dark-speedruns** [comment]
keyboard didnt work
doesnt even let me open the settings.bat

**Comment by donnaken15** [comment]
open a terminal in game directory and run ./FastGH3 -settings`
I don't know if you need to put `wine` before it though

**Comment by kernaltrap8** [comment]
dunno if this will help, but sanjay900 recomended me to do something that fixes his controllers when running games with wine, maybe try it?

```
Wine doesn't like controllers  that don't fit the standard XInput layout, which none of ours do as we expose controllers with all buttons. 
Perform the following actions to disable wines automatic mapping, which will make the controllers work properly

Open regedit in your WINEPREFIX
Navigate to HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\winebus
Create a new DWORD named "Enable SDL" with value 0
Create a new DWORD named "Map Controllers" with value 0```
