### ISSUE TITLE
Bug: Invalid characters in the path.

### ISSUE THREAD

**Issue by Gabiiofficial** [donnaken15/FastGH3#14]
**Summarize**

When I try to open charts, the launcher tells me that there are invalid characters in the chart path. 
I tries to move the files to different paths, but the error persists.

**To Reproduce**
1. Open FastGH3
2. Select a .chart or .mid file
3. Error pops up

**Debugger information (Optional)**
<0,854>System.ArgumentException: Caratteri non validi nel percorso.
   in System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   in System.IO.Path.Combine(String path1, String path2)
   in Program.where(String e)
   in Program.Main(String[] args)

_(Caratteri non validi nel percorso = Invalid characters in the path, in italian)_

**When I downloaded this mod/what version I'm using (most likely required)**
version 1.0-999010889

**Desktop (Optional, but could help figure out system specific problems):**
 - OS: Windows 11

***Do you have these installed: (write an X in the box if you have the following software)***
 - [x] [DirectX 9](http://localhost/fastgh3/redist.php?f=1)
 - [X] [Visual C++ 2005](http://localhost/fastgh3/redist.php?f=2)
 - [X] [.NET Framework 4](http://localhost/fastgh3/redist.php?f=3)

**Comment by donnaken15** [comment]
What does your PATH environment variable look like?

**Comment by Gabiiofficial** [comment]
![Screenshot_1](https://github.com/donnaken15/FastGH3/assets/89658796/4060d1b3-8fce-47bc-af77-22081289cac9)

**Comment by Gabiiofficial** [comment]
![Screenshot_2](https://github.com/donnaken15/FastGH3/assets/89658796/f4f67eff-d665-41ab-ac83-28ea272a4c0f)

**Comment by donnaken15** [comment]
That third path string needs to be fixed (remove "c:\...\javapath;")
I just tested a broken PATH string and got the same error because Windows wraps the path in quotes since there's a semicolon
Will try and see if I can make it autocorrect this kind of mistake anyway

**Comment by Gabiiofficial** [comment]
It worked! Thanks!
