### ISSUE TITLE
Bug: The stage diver had no animation file and caused a segfault on my guitar

### ISSUE THREAD

**Issue by BurAndBY** [donnaken15/FastGH3#15]
**Summarize**
Playing practice on Jordan from enchorus and Trogdor from enchorus just makes the highway fly away when reaching the first note.

**To Reproduce**
1. Open `Strong Bad - Trogdor (Harmonix, Mickelräven)/notes.mid`

**Expected behavior (Optional)**
Highway not flying away 

**Screenshots or attachments**
Launcher.txt - https://bpa.st/QEEQ

**When I downloaded this mod/what version I'm using (most likely required)**
1.1-999011043
Date of download/build date: 07/2024

**What branch of development does this happen on?**
This can be checked from the pause menu. The branch name is read in blue text.<br>
This is only viewable on most recent builds.
 - [X] [main](https://github.com/donnaken15/FastGH3/tree/main)
 - [ ] [unpak](https://github.com/donnaken15/FastGH3/tree/unpak)

**Desktop (Optional, but could help figure out system specific problems):**
 - OS: Win11

***Do you have these installed: (write an X in the box if you have the following software)***
 - [X] [DirectX 9](http://donnaken15.com/fastgh3/redist.php?f=1)
 - [X] [Visual C++ 2005](http://donnaken15.com/fastgh3/redist.php?f=2)
 - [X] [Visual C++ 2015](http://donnaken15.com/fastgh3/redist.php?f=4)
 - [X] [.NET Framework 4](http://donnaken15.com/fastgh3/redist.php?f=3)

**Comment by BurAndBY** [comment]
![image](https://github.com/user-attachments/assets/69156f9a-7ab1-4798-be0a-ce310200949b)
This also happens on other charts (metallica one gh3)

**Comment by donnaken15** [comment]
can you do a screen recording
