### ISSUE TITLE
wiitar wont work / (hack controller detection)

### ISSUE THREAD

**Issue by brenkel** [donnaken15/FastGH3#3]
so my wiitar whitch uses a raphnet adapter wont work on fast gh3, the buttons are completly randomized
red=orange
orange=red
strum down=yellow
select=green
start=blue
i have no idea why this happens but i hope there is a fix

**Comment by donnaken15** [comment]
Is it like that everytime? I thought it'd be "random" based on the gamepad buttons or whatever.
I've had people ask me about this a few times already, and one of them told me they would have to use Key2Joy or X360CE.

**Comment by donnaken15** [comment]
or if that could be based on playing GH3 with the Wiimote but I doubt

**Comment by donnaken15** [comment]
one of the first users that approached me had no problem playing with wiitars besides having to manually enter the game with it
![image](https://user-images.githubusercontent.com/20864393/199832147-f390e180-16b5-4c9b-8a82-7c028b57129d.png)
https://www.youtube.com/watch?v=ddxL27KrLJE&lc=UgxydSA6adJEpr_mh554AaABAg
![image](https://user-images.githubusercontent.com/20864393/199832469-3260ecc5-5d95-4888-b0f6-7b077bb91be5.png)
https://www.youtube.com/watch?v=O1DZgHMoJGQ&lc=UgxMLd6izBY6SZERD7h4AaABAg

**Comment by brenkel** [comment]
how do i use xbox360ce i cant figure out how to map the buttons

**Comment by donnaken15** [comment]
IIRR, the TocaEdit version (if you didn't use that one) allows you to spoof your controller as if it were a guitar
https://drive.google.com/file/d/0B3cd4Ad4P4NiZy1hVzYxUzQ0QlE/view?resourcekey=0-BfvOnrfbTNDzpOPmh_ZTAA

You can hit Record and then press a button on your controller and x360ce will set the selected controller button to that

from Plumato's video:
![image](https://user-images.githubusercontent.com/20864393/199839883-ad5bfe4e-d867-4417-bfe5-d6625ea798ec.png)
![image](https://user-images.githubusercontent.com/20864393/199839935-dd0c110d-2270-440a-aa17-590c4b540cc8.png)

**Comment by donnaken15** [comment]
Plumato's video: https://www.youtube.com/watch?v=tQAp63Z4rys

**Comment by brenkel** [comment]
it works now thanks!
