### ISSUE TITLE
MID2CHARTTTTTT

### ISSUE THREAD

**Issue by donnaken15** [donnaken15/FastGH3#4]
[I DON'T UNDERSTAND THIS!](https://www.youtube.com/watch?v=JHJ08fWByh8&t=882s)

I DON'T HAVE THIS HAPPEN TO ME BUT SOMEHOW IT DOES FOR OTHERS
`System.FormatException: Not a MIDI file - header chunk missing
   at NAudio.Midi.MidiFile..ctor(String filename, Boolean strictChecking)
   at mid2chart.MidReader.ReadMidi(String path, Boolean unforceNAudioStrictMode)
   at mid2chart.Program.Main(String[] args)`
and something about command 0xB0

**Comment by LocalH** [comment]
Workaround is to delete mid2chart.log before feeding a .mid to fastgh3.exe

**Comment by donnaken15** [comment]
Was that log error thing with the "chunk missing" or "command B0"

**Comment by LocalH** [comment]
both, IIRC. But it would do one for a while then suddenly change to the other. I'll try to catch the next time I see a .log file appear before I launch another song, so I don't overwrite it, in case the contents are helpful.

**Comment by donnaken15** [comment]
Regardless, the launcher will print what's in the .log whenever the mid2chart throws, and it would print either of the same thing anyway.


Post-writing: Wait... I think I just realized what I did.

**Comment by donnaken15** [comment]
> Regardless, the launcher will print what's in the .log whenever the mid2chart throws, and it would print either of the same thing anyway.
> 
> Post-writing: Wait... I think I just realized what I did.

a little patch to deal with this
I commented out code that deleted the log first before running mid2chart for some reason
https://github.com/donnaken15/FastGH3/releases/tag/1.0-999010723
