### ISSUE TITLE
bug: for some weird reason only one set of zones works

### ISSUE THREAD

**Issue by brenkel** [donnaken15/FastGH3#5]
so for some weird reason only the rainbow (2012) zones work when i use them i dont know why.
the game just crashes every time i open the game.

**Comment by donnaken15** [comment]
which version are you using that makes this happen
I just reran the latest release build with random zones and it all works

**Comment by brenkel** [comment]
oooh i was running one of the 1.8xxxxxxx versions

**Comment by brenkel** [comment]
btw how do i get an fps display?

**Comment by donnaken15** [comment]
that's not implemented (I can try to), but you can use Fraps or Bandicam to see frame rate
