### ISSUE TITLE
Error message when starting the main program or the updater

### ISSUE THREAD

**Issue by Xane8** [donnaken15/FastGH3#7]
this error:
System.Net.WebException: The remote name could not be resolved: 'donnaken15.tk'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Program.Main(String[] args)

the only thing i could think of was making an exception through the firewall but it did nothing

**Comment by donnaken15** [comment]
my domain registrar is getting screwed over
that part of the launcher is meant to send the log with the error for what actually failed
try the latest download of this mod from (Code > Download as ZIP)

**Comment by donnaken15** [comment]
wait, I realized, this error stems from the updater, and you did not mention that
pushed new commit to use different URL

**Comment by Xane8** [comment]
yeah the latest download fixed that problem sort of because now it outputs an error log
```
ERROR! :(
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Single.Parse(String s)
   at Program.Main(String[] args)
Uploading log.
Log saved to https://0x0.st/HTch.txt
```
also not sure if i'm supposed to be doing this but running register.bat outputs this
```
Creating class keys...
The operation completed successfully.
OK
ERROR: Access is denied.
FAIL
ERROR: Access is denied.
FAIL
ERROR: Access is denied.
FAIL
ERROR: Access is denied.
FAIL
ERROR: Access is denied.
FAIL
ERROR: Access is denied.
FAIL
ERROR: Access is denied.
FAIL
ERROR: Access is denied.
FAIL
ERROR: Access is denied.
FAIL
ERROR: Access is denied.
FAIL
If you see any FAILs here, something went wrong.
This requires running as administrator.
Done.
```
running it as admin makes it close instantly after finishing

**Comment by donnaken15** [comment]
register.bat is ran to automatically make .chart files openable with the mod (when you double click on them)

try redownloading for the Single.Parse fix

**Comment by Xane8** [comment]
yeah that seems to work
maybe unrelated issue but there's no music in practice
and is there some way to unbind esc?

**Comment by donnaken15** [comment]
I don't know why that's happening
the escape bind is forced AFAIK

**Comment by Xane8** [comment]
ok it only happens with a specific song
i'll use this opportunity to ask how to activate autoplay because i can't find it

**Comment by donnaken15** [comment]
enable debug menu from launcher settings, open game, go to debug menu > settings > toggle bot and restart the song

**Comment by Xane8** [comment]
any way to change the sp activations?

**Comment by donnaken15** [comment]
you can specify an array of times for when the bot should execute but you need to edit the song.pak's QB to do that (or changing it internally could work)
the array must be named fastgh3_path_triggers

**Comment by Xane8** [comment]
the song.pak.xen right? what do i use to edit that?

**Comment by Xane8** [comment]
i get this error https://0x0.st/HT2e.txt but i feel like i just did something wrong in qb

**Comment by Xane8** [comment]
i get this
```
ERROR! :(
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Single.Parse(String s)
   at Program.Main(String[] args)
Uploading log.
Log saved to https://0x0.st/HT29.txt
```
and the song.pak gets corrupted (?) changing its size to 176 bytes 

would this be easier to do on discord? if so i'm xane88

**Comment by donnaken15** [comment]
i'm "donnaken15" on discord

**Comment by donnaken15** [comment]
ugh, the code for that is old and doesn't just cancel (progress bar drawing) if it errors
just updated the repo AGAIINNNNNNN
