### ISSUE TITLE
Bug: when changing the difficulty in settings.bat its always forced to expert even when the song has a lower difficulty

### ISSUE THREAD

**Issue by brenkel** [donnaken15/FastGH3#8]
whenever i try and change the difficulty on settings.bat no matter what chart its always expert
like if i where to open the settings.bat file then make the difficulty hard on ode to ocy (which has a hard chart) and close it, it stays on expert even if the settings.bat says the difficulty should be hard.

**Comment by donnaken15** [comment]
I don't get how it would make this happen
What's the Player1 section look like in your INI?

**Comment by brenkel** [comment]
![game no work](https://github.com/donnaken15/FastGH3/assets/117315750/a7303b6a-613c-440f-b76f-76fb35250839)
this is what the player1 ini looks like

**Comment by donnaken15** [comment]
that's the value when you set the difficulty to hard? (0 is easy, 1 is medium, 2 is hard, 3 is expert)

**Comment by brenkel** [comment]
i recently downloaded the newest version and im using the mono bleeding edge version

**Comment by brenkel** [comment]
i tried changing the diff through the ini and it still does expert

**Comment by donnaken15** [comment]
oh FFS, I messed up the config code

try redownloading bleeding edge

https://github.com/donnaken15/FastGH3/commit/9af09df6afffdb464a6aa21b6fa44da297afa1c2

**Comment by brenkel** [comment]
it worked i can use easier difficulties

**Comment by donnaken15** [comment]
yay

**Comment by brenkel** [comment]
uuuuuh i downloaded zones and now the background is white instead of black

**Comment by donnaken15** [comment]
you can try setting a new background image to black to get rid of this
I'll still need to update zones later to not have that anymore
