### ISSUE TITLE
chorus/drive automation plays the wrong song file (.mp3 .opus etc)

### ISSUE THREAD

**Issue by brenkel** [donnaken15/FastGH3#9]
everytime i use chorus/drive automation on some songs it plays the wrong song file
like i see a song on chorus i use the "play in fastgh3" button and soulless 3 plays for the song file instead of the right song file

**Comment by brenkel** [comment]
i have a feeling this only happens with .mp3 songs but im just taking a guess

**Comment by donnaken15** [comment]
what does the folder look like for the song that you're trying to play

**Comment by brenkel** [comment]
well it doesnt happen to one song it happens to a bunch of songs and im pretty sure it only happens if the song uses .mp3

**Comment by brenkel** [comment]
just found out it also happens with .opus files

**Comment by brenkel** [comment]
i also found out is that it happens whithout the drive automation which makes my brain hurted

**Comment by donnaken15** [comment]
How the  launcher determines which audio files to look for is:
If .chart specifies the existing audio streams in its own file (MusicStream, GuitarStream, RhythmStream), it will choose those only and continue on. If the chart has FOF structure files (song,guitar,rhythm named audio files), it looks for those by checking for OGG, then MP3, then WAV, then opus.

**Comment by brenkel** [comment]
ok well then how come the wrong song file plays if it isnt ogg?

**Comment by donnaken15** [comment]
if you have audio files that are MP3 and opus and the same names as each other and want opus, you'll have to rename the MP3 files so the launcher doesn't detect them

**Comment by brenkel** [comment]
no i mean if the song i wanna play doesnt use .ogg then it plays the wrong song file

**Comment by donnaken15** [comment]
is there only a guitar.mp3 file from where you're downloading?

**Comment by brenkel** [comment]
in most songs yes

**Comment by donnaken15** [comment]
rename it to song.mp3

**Comment by brenkel** [comment]
ok but what if im using drive automation?

**Comment by donnaken15** [comment]
pushed a little patch that deals with this stupid thing
it should automatically detect guitar.mp3 and no song.mp3 and put guitar.mp3 as the main track

**Comment by brenkel** [comment]
it works now :D

**Comment by donnaken15** [comment]
is it clearing your drive folder called Z.FGH3$TMP?
